name: compile
run-name: Auto-compiled JAR
on: 
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    id-token: "write"
    contents: "write"
    packages: "write"
    pull-requests: "read"

jobs:
    compile:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            # Checkout actions
            - uses: actions/checkout@v4
            # Setup java 17
            - uses: actions/setup-java@v3
              with:
                distribution: temurin
                java-version: 17
            # Setup gradle
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Give permissions
              run: chmod +x ./gradlew
            # Build grade
            - name: Execute Gradle build
              run: ./gradlew build
            # Upload results as artifact
            - uses: actions/upload-artifact@v3
              with:
                name: Latest Nightly Build
                path: ./build/libs/XyrGr-0.2.0-all.jar
