name: compile
run-name: Auto-compiled JAR
on: 
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
    compile:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            # Checkout actions
            - uses: actions/checkout@v4
            # Setup java 17
            - uses: actions/setup-java@v3
              with:
                distribution: temurin
                java-version: 17
            # Setup gradle
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Give permissions
              run: chmod +x ./gradlew
            # Build grade
            - name: Execute Gradle build
              run: ./gradlew build
#            - name: Remove existing Xyraith.jar
#              run: rm Xyraith.jar
#            - name: Compile with gradle
#              run: ./gradlew shadowJar
#            - name: Commit files
#              run: |
#                git config --local user.name  ${{ github.actor }}
#                git config --local user.email "${{ github.actor }}@users.noreply.github.com"
#                git add Xyraith.jar
#                git commit -m "Auto-compiled JAR"
#                git push